services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN: ${NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN}
    container_name: bio-open-data-dashboard
    ports:
      - "5432:5432"  # Expose PostgreSQL port to host
    volumes:
      - timescale_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bio-dashboard-nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
volumes:
  timescale_data:
