services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL port to host
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data: