services:
  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"  # Expose PostgreSQL port to host
    volumes:
      - timescale_data:/var/lib/postgresql/data

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bio-dashboard-nextjs
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
volumes:
  timescale_data: